### ISSUE TITLE
Building index ahead of time lacks information required for future mapping

### ISSUE THREAD

**Issue by nrempel** [InstantDomain/instant-distance#7]
By building an index ahead of time, the order of the candidates returned are lost. This makes it hard to map an embedding back onto it's originating word if we load the instant-distance instance from a dump.

Unless I'm missing something, does it make sense to add this information to the bincode dump?

**Comment by djc** [comment]
I think we could move something like [the `Index` type](https://github.com/InstantDomain/bolt/blob/main/rust/vectors/src/lib.rs#L25) into instant-distance as an optional higher-level abstraction. Do you think that covers this use case?

How does annoy deal with this? Does it always keep the indexes in order? I have to think about it a bit, but (a) it's important that the HNSW adds items in randomized order and (b) internally we need indexes that map onto the (randomized) insertion order. As such, an additional layer of mapping is unavoidable if we're dealing with a third-party data set (such as in the case of word embeddings) -- that is, we can't reorder the data set after the index creation.

**Comment by nrempel** [comment]
I believe Annoy preserves ordering because the algorithm doesn't require the data to be shuffled. I'm not positive on this, but in my use, it seems to always be the case.

I think it would be useful to move `Index` into instant-distance. However, the MPHF stuff may be a different concern?

**Comment by djc** [comment]
I was thinking we might be able to make do with a simple `Vec`. Will think about it some more.
